import type { ToolCategory, ToolTag } from './types';

export type ConversionMode = 'ai' | 'instant';

export interface ToolConfig {
  id: string;
  name: string;
  shortName: string;
  path: string;
  description: string;
  category: ToolCategory;
  conversionMode: ConversionMode;
  icon: { color: string; label: string };
  inputLanguage: string;
  outputLanguage: string;
  inputFileType: string;
  outputFileType: string;
  inputFileName: string;
  outputFileName: string;
  downloadFileName: string;
  emptyStateMessage: string;
  emptyStateHint: string;
  astFallbackMessage?: string;
  tags: ToolTag[];
}

export interface SidebarCategoryConfig {
  id: ToolCategory;
  label: string;
  toolIds: string[];
}

export const TOOL_CONFIGS: Record<string, ToolConfig> = {
  'js-to-ts': {
    id: 'js-to-ts',
    name: 'JS to TypeScript',
    shortName: 'JS \u2192 TS',
    path: '/js-to-ts',
    description: 'Convert JavaScript/JSX to TypeScript/TSX',
    category: 'typescript',
    conversionMode: 'ai',
    icon: { color: 'hsl(45 85% 50%)', label: 'JS' },
    inputLanguage: 'javascript',
    outputLanguage: 'typescript',
    inputFileType: 'JSX',
    outputFileType: 'TSX',
    inputFileName: 'input.jsx',
    outputFileName: 'output.tsx',
    downloadFileName: 'converted.tsx',
    emptyStateMessage: 'TypeScript output will appear here',
    emptyStateHint: 'Paste code on the left, then hit Convert',
    astFallbackMessage: 'AI models unavailable \u2014 showing basic conversion. Some types may need manual refinement.',
    tags: ['AI-Powered', 'Popular'],
  },
  'json-to-ts': {
    id: 'json-to-ts',
    name: 'JSON to TypeScript',
    shortName: 'JSON \u2192 TS',
    path: '/json-to-typescript',
    description: 'Generate TypeScript interfaces from JSON',
    category: 'typescript',
    conversionMode: 'ai',
    icon: { color: 'hsl(35 85% 45%)', label: '{}' },
    inputLanguage: 'json',
    outputLanguage: 'typescript',
    inputFileType: 'JSON',
    outputFileType: 'TS',
    inputFileName: 'input.json',
    outputFileName: 'output.ts',
    downloadFileName: 'types.ts',
    emptyStateMessage: 'TypeScript interfaces will appear here',
    emptyStateHint: 'Paste JSON on the left, then hit Convert',
    astFallbackMessage: 'AI models unavailable \u2014 showing basic type inference.',
    tags: ['AI-Powered', 'Popular'],
  },
  'json-to-zod': {
    id: 'json-to-zod',
    name: 'JSON to Zod',
    shortName: 'JSON \u2192 Zod',
    path: '/json-to-zod',
    description: 'Generate Zod validation schemas from JSON',
    category: 'json',
    conversionMode: 'ai',
    icon: { color: 'hsl(210 75% 45%)', label: 'ZD' },
    inputLanguage: 'json',
    outputLanguage: 'typescript',
    inputFileType: 'JSON',
    outputFileType: 'ZOD',
    inputFileName: 'input.json',
    outputFileName: 'schema.ts',
    downloadFileName: 'schema.ts',
    emptyStateMessage: 'Zod schema will appear here',
    emptyStateHint: 'Paste JSON on the left, then hit Convert',
    astFallbackMessage: 'AI models unavailable \u2014 showing basic schema generation.',
    tags: ['AI-Powered'],
  },
  'json-to-yaml': {
    id: 'json-to-yaml',
    name: 'JSON to YAML',
    shortName: 'JSON \u2192 YAML',
    path: '/json-to-yaml',
    description: 'Convert JSON to YAML format',
    category: 'json',
    conversionMode: 'instant',
    icon: { color: 'hsl(35 85% 45%)', label: '{}' },
    inputLanguage: 'json',
    outputLanguage: 'yaml',
    inputFileType: 'JSON',
    outputFileType: 'YAML',
    inputFileName: 'input.json',
    outputFileName: 'output.yaml',
    downloadFileName: 'converted.yaml',
    emptyStateMessage: 'YAML output will appear here',
    emptyStateHint: 'Start typing JSON on the left to see live conversion',
    tags: ['Instant'],
  },
  'yaml-to-json': {
    id: 'yaml-to-json',
    name: 'YAML to JSON',
    shortName: 'YAML \u2192 JSON',
    path: '/yaml-to-json',
    description: 'Convert YAML to JSON format',
    category: 'json',
    conversionMode: 'instant',
    icon: { color: 'hsl(280 60% 50%)', label: 'YML' },
    inputLanguage: 'yaml',
    outputLanguage: 'json',
    inputFileType: 'YAML',
    outputFileType: 'JSON',
    inputFileName: 'input.yaml',
    outputFileName: 'output.json',
    downloadFileName: 'converted.json',
    emptyStateMessage: 'JSON output will appear here',
    emptyStateHint: 'Start typing YAML on the left to see live conversion',
    tags: ['Instant'],
  },
  'css-to-json': {
    id: 'css-to-json',
    name: 'CSS to JSON',
    shortName: 'CSS \u2192 JSON',
    path: '/css-to-json',
    description: 'Convert CSS rules to JSON objects (CSS-in-JS)',
    category: 'css',
    conversionMode: 'instant',
    icon: { color: 'hsl(264 70% 50%)', label: 'CS' },
    inputLanguage: 'css',
    outputLanguage: 'json',
    inputFileType: 'CSS',
    outputFileType: 'JSON',
    inputFileName: 'input.css',
    outputFileName: 'styles.json',
    downloadFileName: 'styles.json',
    emptyStateMessage: 'JSON output will appear here',
    emptyStateHint: 'Start typing CSS on the left to see live conversion',
    tags: ['Instant'],
  },
  'js-object-to-json': {
    id: 'js-object-to-json',
    name: 'JS Object to JSON',
    shortName: 'JS Obj \u2192 JSON',
    path: '/js-object-to-json',
    description: 'Convert JS object literals to valid JSON',
    category: 'json',
    conversionMode: 'instant',
    icon: { color: 'hsl(45 85% 50%)', label: 'JS' },
    inputLanguage: 'javascript',
    outputLanguage: 'json',
    inputFileType: 'JS',
    outputFileType: 'JSON',
    inputFileName: 'input.js',
    outputFileName: 'output.json',
    downloadFileName: 'converted.json',
    emptyStateMessage: 'JSON output will appear here',
    emptyStateHint: 'Start typing a JS object on the left to see live conversion',
    tags: ['Instant'],
  },
  'css-to-tailwind': {
    id: 'css-to-tailwind',
    name: 'CSS to Tailwind',
    shortName: 'CSS \u2192 TW',
    path: '/css-to-tailwind',
    description: 'Convert CSS to Tailwind utility classes',
    category: 'css',
    conversionMode: 'ai',
    icon: { color: 'hsl(190 80% 42%)', label: 'TW' },
    inputLanguage: 'css',
    outputLanguage: 'plaintext',
    inputFileType: 'CSS',
    outputFileType: 'TW',
    inputFileName: 'input.css',
    outputFileName: 'output.tw',
    downloadFileName: 'tailwind.txt',
    emptyStateMessage: 'Tailwind classes will appear here',
    emptyStateHint: 'Paste CSS on the left, then hit Convert',
    astFallbackMessage: 'AI models unavailable \u2014 showing basic conversion. Complex CSS properties may need manual review.',
    tags: ['AI-Powered', 'Popular'],
  },
  'scss-to-css': {
    id: 'scss-to-css',
    name: 'SCSS to CSS',
    shortName: 'SCSS \u2192 CSS',
    path: '/scss-to-css',
    description: 'Compile SCSS/SASS to standard CSS',
    category: 'css',
    conversionMode: 'instant',
    icon: { color: 'hsl(330 60% 50%)', label: 'SC' },
    inputLanguage: 'scss',
    outputLanguage: 'css',
    inputFileType: 'SCSS',
    outputFileType: 'CSS',
    inputFileName: 'input.scss',
    outputFileName: 'output.css',
    downloadFileName: 'compiled.css',
    emptyStateMessage: 'Compiled CSS will appear here',
    emptyStateHint: 'Paste SCSS on the left, then hit Convert',
    tags: ['Instant'],
  },
  'html-to-jsx': {
    id: 'html-to-jsx',
    name: 'HTML to JSX',
    shortName: 'HTML \u2192 JSX',
    path: '/html-to-jsx',
    description: 'Convert HTML to valid JSX/TSX for React',
    category: 'react',
    conversionMode: 'instant',
    icon: { color: 'hsl(15 85% 50%)', label: 'HT' },
    inputLanguage: 'html',
    outputLanguage: 'javascript',
    inputFileType: 'HTML',
    outputFileType: 'JSX',
    inputFileName: 'input.html',
    outputFileName: 'output.jsx',
    downloadFileName: 'component.jsx',
    emptyStateMessage: 'JSX output will appear here',
    emptyStateHint: 'Start typing HTML on the left to see live conversion',
    tags: ['Instant', 'Popular'],
  },
  'tailwind-to-css': {
    id: 'tailwind-to-css',
    name: 'Tailwind to CSS',
    shortName: 'TW \u2192 CSS',
    path: '/tailwind-to-css',
    description: 'Reverse Tailwind utilities to vanilla CSS',
    category: 'css',
    conversionMode: 'ai',
    icon: { color: 'hsl(190 80% 42%)', label: 'TW' },
    inputLanguage: 'html',
    outputLanguage: 'css',
    inputFileType: 'TW',
    outputFileType: 'CSS',
    inputFileName: 'input.html',
    outputFileName: 'output.css',
    downloadFileName: 'styles.css',
    emptyStateMessage: 'CSS output will appear here',
    emptyStateHint: 'Paste Tailwind classes on the left, then hit Convert',
    astFallbackMessage: 'AI models unavailable \u2014 showing basic conversion.',
    tags: ['Instant'],
  },
  'graphql-to-ts': {
    id: 'graphql-to-ts',
    name: 'GraphQL to TypeScript',
    shortName: 'GQL \u2192 TS',
    path: '/graphql-to-typescript',
    description: 'Generate TypeScript types from GraphQL schemas',
    category: 'typescript',
    conversionMode: 'ai',
    icon: { color: 'hsl(320 70% 50%)', label: 'GQ' },
    inputLanguage: 'graphql',
    outputLanguage: 'typescript',
    inputFileType: 'GQL',
    outputFileType: 'TS',
    inputFileName: 'schema.graphql',
    outputFileName: 'types.ts',
    downloadFileName: 'types.ts',
    emptyStateMessage: 'TypeScript types will appear here',
    emptyStateHint: 'Paste GraphQL schema on the left, then hit Convert',
    astFallbackMessage: 'AI models unavailable \u2014 showing basic type generation.',
    tags: ['AI-Powered'],
  },
  'proptypes-to-ts': {
    id: 'proptypes-to-ts',
    name: 'PropTypes to TypeScript',
    shortName: 'PT \u2192 TS',
    path: '/proptypes-to-typescript',
    description: 'Convert React PropTypes to TypeScript interfaces',
    category: 'typescript',
    conversionMode: 'ai',
    icon: { color: 'hsl(200 80% 50%)', label: 'PT' },
    inputLanguage: 'javascript',
    outputLanguage: 'typescript',
    inputFileType: 'JSX',
    outputFileType: 'TSX',
    inputFileName: 'input.jsx',
    outputFileName: 'output.tsx',
    downloadFileName: 'component.tsx',
    emptyStateMessage: 'TypeScript output will appear here',
    emptyStateHint: 'Paste PropTypes component on the left, then hit Convert',
    astFallbackMessage: 'AI models unavailable \u2014 showing basic PropTypes conversion.',
    tags: ['AI-Powered'],
  },
  'sql-to-ts': {
    id: 'sql-to-ts',
    name: 'SQL to TypeScript',
    shortName: 'SQL \u2192 TS',
    path: '/sql-to-typescript',
    description: 'Generate TypeScript types from SQL schemas',
    category: 'typescript',
    conversionMode: 'ai',
    icon: { color: 'hsl(210 60% 50%)', label: 'SQ' },
    inputLanguage: 'sql',
    outputLanguage: 'typescript',
    inputFileType: 'SQL',
    outputFileType: 'TS',
    inputFileName: 'schema.sql',
    outputFileName: 'types.ts',
    downloadFileName: 'types.ts',
    emptyStateMessage: 'TypeScript types will appear here',
    emptyStateHint: 'Paste SQL schema on the left, then hit Convert',
    astFallbackMessage: 'AI models unavailable \u2014 showing basic type generation from SQL.',
    tags: ['AI-Powered'],
  },
  'openapi-to-ts': {
    id: 'openapi-to-ts',
    name: 'OpenAPI to TypeScript',
    shortName: 'API \u2192 TS',
    path: '/openapi-to-typescript',
    description: 'Generate TypeScript types from OpenAPI/Swagger specs',
    category: 'typescript',
    conversionMode: 'ai',
    icon: { color: 'hsl(145 60% 42%)', label: 'AP' },
    inputLanguage: 'json',
    outputLanguage: 'typescript',
    inputFileType: 'API',
    outputFileType: 'TS',
    inputFileName: 'openapi.json',
    outputFileName: 'types.ts',
    downloadFileName: 'types.ts',
    emptyStateMessage: 'TypeScript types will appear here',
    emptyStateHint: 'Paste OpenAPI spec on the left, then hit Convert',
    astFallbackMessage: 'AI models unavailable \u2014 showing basic type generation from OpenAPI.',
    tags: ['AI-Powered'],
  },
};

export const SIDEBAR_CATEGORIES: SidebarCategoryConfig[] = [
  {
    id: 'typescript',
    label: 'TypeScript',
    toolIds: ['js-to-ts', 'json-to-ts', 'graphql-to-ts', 'proptypes-to-ts', 'sql-to-ts', 'openapi-to-ts'],
  },
  {
    id: 'json',
    label: 'JSON',
    toolIds: ['json-to-yaml', 'yaml-to-json', 'json-to-zod', 'js-object-to-json'],
  },
  {
    id: 'css',
    label: 'CSS',
    toolIds: ['css-to-tailwind', 'tailwind-to-css', 'css-to-json', 'scss-to-css'],
  },
  {
    id: 'react',
    label: 'React',
    toolIds: ['html-to-jsx'],
  },
];

export function getToolConfig(toolId: string): ToolConfig | undefined {
  return TOOL_CONFIGS[toolId];
}

export function getToolByPath(path: string): ToolConfig | undefined {
  return Object.values(TOOL_CONFIGS).find((t) => t.path === path);
}
