import type { SqlToTsOptions, SqlToTsStats } from '../types';

// SQL type → TypeScript type mapping
const TYPE_MAP: Record<string, string> = {
  // Integers
  int: 'number',
  integer: 'number',
  bigint: 'number',
  smallint: 'number',
  tinyint: 'number',
  mediumint: 'number',
  serial: 'number',
  bigserial: 'number',
  smallserial: 'number',
  // Floats
  decimal: 'number',
  numeric: 'number',
  float: 'number',
  double: 'number',
  real: 'number',
  money: 'number',
  'double precision': 'number',
  // Strings
  varchar: 'string',
  char: 'string',
  text: 'string',
  nvarchar: 'string',
  nchar: 'string',
  clob: 'string',
  uuid: 'string',
  citext: 'string',
  name: 'string',
  // Boolean
  boolean: 'boolean',
  bool: 'boolean',
  // Date/time (resolved dynamically based on options)
  date: '__date__',
  datetime: '__date__',
  timestamp: '__date__',
  timestamptz: '__date__',
  'timestamp without time zone': '__date__',
  'timestamp with time zone': '__date__',
  time: 'string',
  timetz: 'string',
  interval: 'string',
  // JSON
  json: 'Record<string, unknown>',
  jsonb: 'Record<string, unknown>',
  // Binary
  blob: 'Buffer',
  bytea: 'Buffer',
  binary: 'Buffer',
  varbinary: 'Buffer',
  // Other
  xml: 'string',
  inet: 'string',
  cidr: 'string',
  macaddr: 'string',
  point: '{ x: number; y: number }',
  line: 'string',
  polygon: 'string',
  circle: 'string',
  box: 'string',
  path: 'string',
  tsquery: 'string',
  tsvector: 'string',
};

// Columns that are typically auto-generated
const AUTO_GENERATED_PATTERNS = [
  /^id$/i,
  /^created[_-]?at$/i,
  /^updated[_-]?at$/i,
  /^modified[_-]?at$/i,
  /^deleted[_-]?at$/i,
];

interface ParsedColumn {
  name: string;
  tsType: string;
  nullable: boolean;
  isAutoGenerated: boolean;
  hasDefault: boolean;
  isPrimaryKey: boolean;
  references?: { table: string; column: string };
}

interface ParsedTable {
  name: string;
  columns: ParsedColumn[];
  foreignKeys: { column: string; refTable: string; refColumn: string }[];
}

function toPascalCase(str: string): string {
  return str
    .replace(/[_-]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .replace(/\s+/g, '');
}

function resolveEnumType(enumDef: string): string {
  const values = enumDef.match(/'([^']+)'/g);
  if (!values) return 'string';
  return values.map((v) => v).join(' | ');
}

function resolveSqlType(rawType: string, options: SqlToTsOptions): string {
  const lower = rawType.toLowerCase().trim();

  // Handle ENUM type
  const enumMatch = lower.match(/^enum\s*\((.+)\)$/);
  if (enumMatch) return resolveEnumType(enumMatch[1]);

  // Handle array types (PostgreSQL)
  const arrayMatch = lower.match(/^(.+)\[\]$/);
  if (arrayMatch) {
    const inner = resolveSqlType(arrayMatch[1], options);
    return `${inner}[]`;
  }

  // Handle type with size params: VARCHAR(255), DECIMAL(10,2)
  const baseType = lower.replace(/\s*\([^)]*\)/, '').trim();

  const mapped = TYPE_MAP[baseType];
  if (mapped === '__date__') {
    return options.dateHandling === 'date-object' ? 'Date' : 'string';
  }
  if (mapped) return mapped;

  // Fallback
  return 'unknown';
}

function parseColumnLine(
  line: string,
  options: SqlToTsOptions,
): ParsedColumn | null {
  const trimmed = line.trim().replace(/,$/, '');
  if (!trimmed) return null;

  // Skip constraint lines
  if (/^\s*(CONSTRAINT|PRIMARY\s+KEY|UNIQUE|CHECK|INDEX|KEY\s)/i.test(trimmed)) return null;
  // Skip FOREIGN KEY constraint lines
  if (/^\s*FOREIGN\s+KEY/i.test(trimmed)) return null;

  // Parse: column_name TYPE [constraints...]
  const match = trimmed.match(
    /^[`"']?(\w+)[`"']?\s+(.+)$/,
  );
  if (!match) return null;

  const name = match[1];
  const rest = match[2];

  // Extract the SQL type (everything before the first constraint keyword)
  const typeMatch = rest.match(
    /^((?:(?:double\s+precision|timestamp\s+(?:with|without)\s+time\s+zone)|[\w\s]+?)(?:\([^)]*\))?(?:\[\])?)\s*(.*)?$/i,
  );
  if (!typeMatch) return null;

  const rawType = typeMatch[1].trim();
  const constraints = (typeMatch[2] || '').toUpperCase();

  const tsType = resolveSqlType(rawType, options);
  const isNotNull = constraints.includes('NOT NULL');
  const isPrimaryKey = constraints.includes('PRIMARY KEY');
  const hasDefault = constraints.includes('DEFAULT');
  const isSerial = /^(big)?serial$/i.test(rawType.replace(/\([^)]*\)/, '').trim());
  const isAutoIncrement = constraints.includes('AUTO_INCREMENT') || constraints.includes('AUTOINCREMENT');

  // Detect inline REFERENCES
  let references: { table: string; column: string } | undefined;
  const refMatch = rest.match(/REFERENCES\s+[`"']?(\w+)[`"']?\s*\(\s*[`"']?(\w+)[`"']?\s*\)/i);
  if (refMatch) {
    references = { table: refMatch[1], column: refMatch[2] };
  }

  const isAutoGenerated =
    isPrimaryKey ||
    isSerial ||
    isAutoIncrement ||
    AUTO_GENERATED_PATTERNS.some((p) => p.test(name)) ||
    (hasDefault && /DEFAULT\s+(NOW|CURRENT_TIMESTAMP|CURRENT_DATE)/i.test(rest));

  return {
    name,
    tsType,
    nullable: !isNotNull && !isPrimaryKey,
    isAutoGenerated,
    hasDefault,
    isPrimaryKey,
    references,
  };
}

function parseForeignKeys(body: string): { column: string; refTable: string; refColumn: string }[] {
  const fks: { column: string; refTable: string; refColumn: string }[] = [];
  const regex = /FOREIGN\s+KEY\s*\(\s*[`"']?(\w+)[`"']?\s*\)\s*REFERENCES\s+[`"']?(\w+)[`"']?\s*\(\s*[`"']?(\w+)[`"']?\s*\)/gi;
  let match;
  while ((match = regex.exec(body)) !== null) {
    fks.push({ column: match[1], refTable: match[2], refColumn: match[3] });
  }
  return fks;
}

function parseCreateTables(sql: string): { name: string; body: string }[] {
  const tables: { name: string; body: string }[] = [];
  const regex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[`"']?(\w+)[`"']?\s*\(([\s\S]*?)\)\s*;/gi;
  let match;
  while ((match = regex.exec(sql)) !== null) {
    tables.push({ name: match[1], body: match[2] });
  }
  return tables;
}

function splitColumns(body: string): string[] {
  const lines: string[] = [];
  let depth = 0;
  let current = '';

  for (const char of body) {
    if (char === '(') depth++;
    else if (char === ')') depth--;

    if (char === ',' && depth === 0) {
      lines.push(current.trim());
      current = '';
    } else {
      current += char;
    }
  }
  if (current.trim()) lines.push(current.trim());
  return lines;
}

function formatNullable(tsType: string, nullable: boolean, options: SqlToTsOptions): string {
  if (!nullable) return tsType;
  if (options.nullableStyle === 'optional') return tsType;
  return `${tsType} | null`;
}

function generateInterface(
  table: ParsedTable,
  options: SqlToTsOptions,
  mode: 'select' | 'insert',
): string {
  const typeName = toPascalCase(table.name);
  const prefix = mode === 'insert' ? 'Insert' : '';
  const name = `${prefix}${typeName}`;

  const lines: string[] = [];
  lines.push(`export interface ${name} {`);

  for (const col of table.columns) {
    const isOptionalInInsert = mode === 'insert' && (col.isAutoGenerated || col.hasDefault || col.nullable);
    const optional = mode === 'insert'
      ? isOptionalInInsert
      : options.nullableStyle === 'optional' && col.nullable;
    const type = formatNullable(col.tsType, col.nullable, options);
    const optMark = optional ? '?' : '';
    lines.push(`  ${col.name}${optMark}: ${type};`);
  }

  lines.push('}');
  return lines.join('\n');
}

export function sqlToTsAst(
  sql: string,
  options: SqlToTsOptions,
): { code: string; stats: SqlToTsStats } {
  const stats: SqlToTsStats = {
    tablesConverted: 0,
    columnsTyped: 0,
    foreignKeysDetected: 0,
    enumsGenerated: 0,
  };

  const rawTables = parseCreateTables(sql);
  if (rawTables.length === 0) {
    return {
      code: '// No CREATE TABLE statements found',
      stats,
    };
  }

  const tables: ParsedTable[] = [];

  for (const raw of rawTables) {
    const columnLines = splitColumns(raw.body);
    const columns: ParsedColumn[] = [];
    const foreignKeys = parseForeignKeys(raw.body);

    for (const line of columnLines) {
      const col = parseColumnLine(line, options);
      if (col) {
        // Merge standalone FK refs into column
        const fk = foreignKeys.find((f) => f.column === col.name);
        if (fk && !col.references) {
          col.references = { table: fk.refTable, column: fk.refColumn };
        }
        columns.push(col);
        stats.columnsTyped++;

        // Count enums
        if (col.tsType.includes(' | ') && col.tsType.includes("'")) {
          stats.enumsGenerated++;
        }
      }
    }

    stats.foreignKeysDetected += foreignKeys.length;
    // Also count inline refs not in standalone FK constraints
    for (const col of columns) {
      if (col.references && !foreignKeys.some((f) => f.column === col.name)) {
        stats.foreignKeysDetected++;
      }
    }

    stats.tablesConverted++;
    tables.push({ name: raw.name, columns, foreignKeys });
  }

  const output: string[] = [];

  for (const table of tables) {
    output.push(generateInterface(table, options, 'select'));

    if (options.generateMode === 'select-insert') {
      output.push(generateInterface(table, options, 'insert'));
    }
  }

  return {
    code: output.join('\n\n'),
    stats,
  };
}
